### ISSUE TITLE
[Bug]: Unable to see icons in Menu Bar Layout Settings

### ISSUE THREAD

**Issue by Joemnewton** [jordanbaird/Ice#761]
### Search for Similar Reports

- [x] I have searched existing issues for similar reports

### Description

When I go to Settings -> Menu Bar Layout, I cannot see any icons to move. Each section is just white..

### Steps to Reproduce

1. Open Ice Settings
2. Click Menu Bar Layout
3. Look at the blank white rows instead of seeing the icons

### App Version

0.11.12

### macOS Version

26.0.1

### Additional Information

<img width="995" height="738" alt="Image" src="https://github.com/user-attachments/assets/d91cd7da-cc5f-4194-ab9e-a4dc25d85e9f" />

**Comment by rasmusbe** [comment]
Solved in the beta
https://github.com/jordanbaird/Ice/releases/tag/0.11.13-dev.2

**Comment by jbjb4467** [comment]
I enabled the Show menu bar background option in System Settings > Menu Bar, but I cannot see any icons yet.

<img width="892" height="617" alt="Image" src="https://github.com/user-attachments/assets/15d328f8-0cd0-48cb-ae9e-db4173d0ec4a" />

**Comment by tdeniston** [comment]
That doesn't look like the beta to me. Try beta version 0.11.13-dev.2. See discussion https://github.com/jordanbaird/Ice/discussions/672

**Comment by ic-jw-msp** [comment]
Hi, unfortunately, I'm still having the same issues on the latest beta. Any help would be appreciated. 

<img width="2024" height="1474" alt="Image" src="https://github.com/user-attachments/assets/e20436de-fab7-408a-9a21-dfc71e4a1b48" />
<img width="2024" height="1474" alt="Image" src="https://github.com/user-attachments/assets/c1371354-e24d-417e-91cc-3795260eb56c" />

**Comment by jhult** [comment]
Dupe of #744 and #743

**Comment by jamesdh** [comment]
I was experiencing the same until updating to 0.11.13-dev.2, now I see the same issue as @ic-jw-msp where it says "Unable to display menu bar items".

**Comment by jamesdh** [comment]
Related: https://github.com/jordanbaird/Ice/discussions/672#discussioncomment-14423221

**Comment by meden** [comment]
I think [this comment](https://github.com/jordanbaird/Ice/discussions/672#discussioncomment-14625055) has the key.

TL;DR: It may be caused by having the option _Displays have separate Spaces_ disabled.

I'm using the same configuration and I have the issue. I could not test with the option enabled yet, though.

**Comment by kmnola** [comment]
> TL;DR: It may be caused by having the option Displays have separate Spaces disabled.

I'm currently using dev.1 because it *sort of* works... but I have both installers downloaded.  I'm going to try this fix and see if it works!  Will report back.

EDIT:  Holy crap!  That seems to have worked!!  I only use one display so it's not a big deal for me to leave that enabled, but I'm curious what that is doing that fixes it?

Second edit:  The only part that is bothering me - and this is seriously nit picky.  Is that there's only one possible divider symbol. Before you used to be able to use like a chevron, or a dot, or I think a line.  Now it's just the chevron option.  I don't know if that's a bug or if it's just not been programmed in yet. I can live with it though.

**Comment by jamesdh** [comment]
Can confirm re-enabling "Displays have separate Spaces" fixed this. Kinda of a bummer (for other reasons) but I'll live with it.

**Comment by adriangalilea** [comment]
> Can confirm re-enabling "Displays have separate Spaces" fixed this. Kinda of a bummer (for other reasons) but I'll live with it.

I’m on the last stable version and it doesn’t work regardless of this setting.

Also if I change this setting, another app I use constantly, `Swish`, stops working well.

**Comment by jamesdh** [comment]
@adriangalilea in addition to that setting, you need to use the beta (e.g. `brew install jordanbaird-ice@beta`) and not the latest stable version. 

In any case it's still a bug and can hopefully be resolved so those of us that prefer not having separate spaces for each display can return to that setting.

**Comment by adriangalilea** [comment]
@jamesdh Thanks for the info, will wait for it to not require the workaround since it messes with software I depend on.
